# Generated by Django 5.2.8 on 2025-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor_nombre', models.CharField(max_length=100, verbose_name='Nombre del autor')),
                ('autor_apellidos', models.CharField(max_length=150, verbose_name='Apellidos del autor')),
                ('genero', models.CharField(max_length=100)),
                ('paginas', models.PositiveIntegerField()),
            ],
        ),
    ]
